nginx:
    build: ./nginx
    links:
        - client1:client1
        - client2:client2
        - gateway1:gateway1
        - gateway2:gateway2
    ports:
        - "80:80"

client1:
    build: ./client
    ports:
        - "8080"
client2:
    build: ./client
    ports:
        - "8080"

gateway1:
    build: ./gateway
    ports:
        - "4747"
    links:
        - scoring:scoring
        - auth:auth
        - main:main
gateway2:
    build: ./gateway
    ports:
        - "4747"
    links:
        - scoring:scoring
        - auth:auth
        - main:main

scoring:
    build: ./scoring
    ports:
        - "5000"
auth:
    build: ./auth
    ports:
        - "3000"
    links:
        - database:database
main:
    build: ./main
    ports:
        - "8000"
    links:
        - database:database

database:
    image: mongo
    ports:
        - "27017"
        - "28017"