nginx:
    build: ./nginx
    links:
        - client1:client1
        - client2:client2
    ports:
        - "80:80"
client1:
    build: ./client
    ports:
        - "8080"
    links:
        - loadbalancer
        - database:database
client2:
    build: ./client
    ports:
        - "8080"
    links:
        - loadbalancer
        - database:database

loadbalancer:
    build: ./loadbalancer
    links:
        - gateway1:gateway1
        - gateway2:gateway2
    ports:
        - "4747:4747"
gateway1:
    build: ./gateway
    ports:
        - "4748"
    links:
        - scoring:scoring
gateway2:
    build: ./gateway
    ports:
        - "4748"
    links:
        - scoring:scoring

scoring:
    build: ./scoring
    ports:
        - "5000"

database:
    image: mongo
    ports:
        - "27017"
        - "28017"