nginx:
    build: ./nginx
    links:
        - client1:client1
        - client2:client2
    ports:
        - "80:80"
client1:
    build: ./client
    ports:
        - "8080"
    links:
        - gateway
        - database:database
client2:
    build: ./client
    ports:
        - "8080"
    links:
        - gateway
gateway:
    build: ./gateway
    ports:
        - "4747:4747"
    links:
        - scoring:scoring
scoring:
    build: ./scoring
    ports:
        - "5000"
database:
    image: mongo
    ports:
        - "27017"
        - "28017"